### ISSUE TITLE
`download_post()` save to folder with custom path bug

### ISSUE THREAD

**Issue by hirusha-adi** [instaloader/instaloader#1489]
**Describe the bug**
`Post.download_post()` issue when saving the post to a custom folder passed to `target` paramater

**To Reproduce**
run this simplified python code

```python
from instaloader import Instaloader, Profile
import os

TARGET = "Any-Username"

# Create object
insta = Instaloader()

# Login
insta.login(user="username", passwd="password")

# Set Username
profile = Profile.from_username(
    insta.context,
    TARGET
)

# Get Posts
uploaded_posts = profile.get_posts()

# custom save folder
save_folder = os.path.join(
    "static",
    "data",
    TARGET,
    "posts",
    "uploaded"
)
if not(os.path.isdir(save_folder)):
    os.makedirs(save_folder)

# Start Saving posts with a count
count = 1
for post in uploaded_posts:
    print(count)
    # print(
    # f"[{count}]: Title: {post.title}\n\tCaption: {post.caption}\n\tDate: {post.date}\n\tURL:{post.url}\n")
    insta.download_post(
        post,
        target=save_folder
    )

```

**Expected behavior**
`target` is being treated as one directory name and not as a directory inside another directory...

these files should be inside the folder which is pointed by the arrow, but is in a directory with the needed path as the name of that directory

![image](https://user-images.githubusercontent.com/36286877/163108187-337b8359-ec9e-4eb1-987e-697b6c0f63af.png)

its supposed to be the same folder
![image](https://user-images.githubusercontent.com/36286877/163109073-a6ae4e04-a84a-4191-bd1b-fc6c80ceedd7.png)

-------------------------------

Python too says that these are two different things

```python
>>> x
'∕mnt∕B84CC2894CC241BC∕development∕Python∕Instagram-Grabber∕static∕data∕maneshsamarathunga∕posts∕uploaded/'
>>> y
'/mnt/B84CC2894CC241BC/development/Python/Instagram-Grabber/static/data/maneshsamarathunga/posts/uploaded/'
>>> x == y
False
```

**Error messages and tracebacks**
None.

**Instaloader version**
`4.9`

**Comment by miriq** [comment]
This is probably caused by this line, but not sure how or where:

https://github.com/instaloader/instaloader/blob/218d88fc6d7e981676e5ce0c0ea47ffd99ee27fb/instaloader/instaloader.py#L155-L157

**Comment by hirusha-adi** [comment]
> caused by this line

yes, `\u2215` looks the same. Is there any way to disable this?

**Comment by Thammus** [comment]
To specify a custom download folder, use [dirname_pattern](https://instaloader.github.io/basic-usage.html#filename-specification), like e.g.

```python
# Create object
insta = Instaloader(dirname_pattern='static/data/{target}/posts/uploaded')

#
# [...]
#
    insta.download_post(
        post,
        target=TARGET
    )
```

**Comment by hirusha-adi** [comment]
fixed, thank you!

**Comment by k12978** [comment]
> This is probably caused by this line, but not sure how or where:
> 
> https://github.com/instaloader/instaloader/blob/218d88fc6d7e981676e5ce0c0ea47ffd99ee27fb/instaloader/instaloader.py#L155-L157

Why is this the default?

**Comment by hirusha-adi** [comment]
No idea... Why not use: os.path.join to get the path?

**Comment by k12978** [comment]
> No idea... Why not use: os.path.join to get the path?

I was but the problem persisted; I ended up using the solution Thammus added along with os.path.join. I think the code should be reviewed because it causing this problem for you on Linux and me on Windows.

**Comment by Bill-tw** [comment]
up until today 20240726 i'm still facing the same issue. is there a reason why this aint get fixed?

**Comment by silascmv** [comment]
I resolved with this. 

def download_reels(username):
        load_dotenv()
        download_path = os.getenv("PATH_DOWNLOAD")
        temp_subdir = tempfile.mkdtemp(dir='./' + download_path)
        print('------------------->',temp_subdir)
        folder_name = os.path.basename(temp_subdir)
        print('--------->',folder_name)
        """Baixa os Reels do perfil do Instagram e cria um arquivo ZIP."""
        loader = instaloader.Instaloader(dirname_pattern='downloads/' + folder_name)
        downloaded_files = []
        try:
            # Carrega o perfil do usuário
            profile = instaloader.Profile.from_username(loader.context, username)
            print(f"Baixando todos os Reels do usuário {username}...")
 
            for post in profile.get_posts():
                    time.sleep(5)  # Pausa para não sobrecarregar o servidor
                    if post.is_video and post.typename == "GraphVideo":
                        loader.download_post(post,target=temp_subdir)
            

        except instaloader.exceptions.ProfileNotExistsException:
            print(f"O perfil '{self.usernamesearch}' não existe.")
        except instaloader.exceptions.LoginRequiredException:
            print("Login necessário para acessar esse perfil.")
        except instaloader.exceptions.TwoFactorAuthRequiredException:
            print("Autenticação em dois fatores é necessária.")
        except instaloader.exceptions.BadCredentialsException:
            print("Credenciais inválidas.")
        except instaloader.exceptions.ConnectionException:
            print("Problema de conexão.")
        except Exception as e:
            print(f"Erro inesperado: {e}")
