### ISSUE TITLE
Error 401 - Unauthorized "fail" status, message "Please wait a few minutes before you try again."

### ISSUE THREAD

**Issue by randomuser3463** [instaloader/instaloader#2511]
**Describe the bug**
Shows the same 401 error no matter what task is being done, what IP I use, whether I'm logged in, regardless of the account I use, regardless of the cookies I use or regardless of the script itself, ALWAYS the same 401 "unauthorized" error. It first started doing it a month ago and is still doing it to this day without a fix.

**To Reproduce**
Do literally anything with instaloader

**Expected behavior**
Download pictures, scrape usernames or literally anything

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

**Instaloader version**
4.14

![Image](https://github.com/user-attachments/assets/13b04f40-981d-4e0d-930b-dfceda5e5d6d)

**Comment by Showmaster3000** [comment]
Seems duplicate of #2307.

**Comment by randomuser3463** [comment]
> Seems duplicate of [#2307](https://github.com/instaloader/instaloader/issues/2307).

No for me it gives me the error IMMEDIATELY after starting and not after 12 downloads or whatever

**Comment by ChiragNSundar** [comment]
i'm getting the same error

**Comment by voivodeship** [comment]
I'm getting this error as well for the last few days. On Friday it was working fine. Other scrapers are working fine for me. I'm not logged in and it doesn't matter what username I search for, whether I use filters or not.

When not using any filters, the program downloads a profile ID, will download the profile pic, then will give that error when trying to download the actual posts. With a private profile, it will give the login required error and not any of the 401 errors.

> C:\Users\USER\Desktop\Funny\>instaloader username9999
> Stored ID 11111111111 for profile username9999.
> Hint: Login to download higher-quality versions of pictures.
> [1/1] Downloading profile username9999
> username9999\2024-10-23_26-42-16_UTC_profile_pic.jpg
> Retrieving posts from profile username9999.
> JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
> JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22data%22%3A%7B%22count%22%3A12%2C%22include_relationship_info%22%3Atrue%2C%22latest_besties_reel_media%22%3Atrue%2C%22latest_reel_media%22%3Atrue%7D%2C%22username%22%3A%22username9999%22%2C%22__relay_internal__pv__PolarisFeedShareMenurelayprovider%22%3Afalse%7D&doc_id=7898261790222653&server_timestamps=true [retrying; skip with ^C]
> username9999: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22data%22%3A%7B%22count%22%3A12%2C%22include_relationship_info%22%3Atrue%2C%22latest_besties_reel_media%22%3Atrue%2C%22latest_reel_media%22%3Atrue%7D%2C%22username%22%3A%22username9999%22%2C%22__relay_internal__pv__PolarisFeedShareMenurelayprovider%22%3Afalse%7D&doc_id=7898261790222653&server_timestamps=true

**Comment by FalxGod** [comment]
Fix for python module using a venv
I fixed this issue by following a post from a similar post about Unathorizied access.
Login with this;
L.load_session("lucysharke10", {
    "csrftoken": "Token",
    "sessionid": "Token",
    "ds_user_id": "Token",
    "mid": "Token",
    "ig_did": "Token"
})
Get the tokens from browser cookie store after logging into Insta.

Go into your .venv/Lib/site-packages/instaloader folder.
Open instaloadercontext.py
Seach for "def login(self, user, passwd):"
Delete 'sessionid': '', from
```
session.cookies.update({'sessionid': '', 'mid': '', 'ig_pr': '1',
                                'ig_vw': '1920', 'ig_cb': '1', 'csrftoken': '',
                                's_network': '', 'ds_user_id': ''})
```
so you get:
```
session.cookies.update({'mid': '', 'ig_pr': '1',
                                'ig_vw': '1920', 'ig_cb': '1', 'csrftoken': '',
                                's_network': '', 'ds_user_id': ''})
```

**Comment by voivodeship** [comment]
@FalxGod 

Would it be possible to use this fix without actually logging in? I know that the issue I'm having isn't a login issue, considering other scrappers are working fine downloading full profiles without authentication.

**Comment by xathian** [comment]
> [@FalxGod](https://github.com/FalxGod)
> 
> Would it be possible to use this fix without actually logging in? I know that the issue I'm having isn't a login issue, considering other scrappers are working fine downloading full profiles without authentication.

Which other scrapers work without authentication? The only one I know of that still works is gallery-dl and that requires a login cookie

**Comment by Darkaxt** [comment]
Changing instaloadercontext.py didn't solve my issue and I do not understand the section of L.load_session....

**Comment by FalxGod** [comment]
> [@FalxGod](https://github.com/FalxGod)
> 
> Would it be possible to use this fix without actually logging in? I know that the issue I'm having isn't a login issue, considering other scrappers are working fine downloading full profiles without authentication.

Just saw your coment, I'll take a look into the code once I'm home from work. Gimme ~6h and I'll report back.

**Comment by Always-Be-Positive** [comment]
I am getting the same error for several days for now. Could you please share the solution if you have found any? Thank you so much!

**Comment by nadermx** [comment]
> > [@FalxGod](https://github.com/FalxGod)
> > Would it be possible to use this fix without actually logging in? I know that the issue I'm having isn't a login issue, considering other scrappers are working fine downloading full profiles without authentication.
> 
> Which other scrapers work without authentication? The only one I know of that still works is gallery-dl and that requires a login cookie

gallery-dl doesn't require you to be logged in to use it.

**Comment by Always-Be-Positive** [comment]
I get the same error message from gallery-dl as well.

$ gallery-dl 'www.instagram.com/google'
[instagram][error] HttpError: '401 Unauthorized' for 'https://www.instagram.com/api/v1/users/web_profile_info/'

> > > [@FalxGod](https://github.com/FalxGod)
> > > Would it be possible to use this fix without actually logging in? I know that the issue I'm having isn't a login issue, considering other scrappers are working fine downloading full profiles without authentication.
> > 
> > 
> > Which other scrapers work without authentication? The only one I know of that still works is gallery-dl and that requires a login cookie
> 
> gallery-dl doesn't require you to be logged in to use it.

**Comment by EchterAlsFake** [comment]
I don't know if I am stupid, but when looking into the upcoming v4.15 branch you can see that aandergr pushed a commit where he changed the chrome user agent from version 127 to 132.

Here's the commit: https://github.com/instaloader/instaloader/commit/a263ec85a6640903f24a95ba0109d313c9cfbb49

So I just installed this version of instaloader with `pip install git+https://github.com/instaloader/instaloader@upcoming/v4.15` and everything worked first try. Fetching posts, logging and, fetching highlights... No problems with it.

Already fetched over 200 images, so I don't know if I am just lucky, but maybe cou can try this out and see it it helps you :)

**Comment by Rohitseelam** [comment]
Hey @EchterAlsFake,

installed the version you mentioned above. Can you look at the code below if i am missing something ?

`from instaloader import Instaloader, Profile
import os

# Create directory if not exists
SESSION_DIR = "C:/Users/Shree/Desktop/Insta/Sessions"
os.makedirs(SESSION_DIR, exist_ok=True)

L = Instaloader(download_pictures=True, save_metadata=True, compress_json=True, quiet=False)

USERNAME = "xyzz"
SESSION_PATH = os.path.join(SESSION_DIR, f"session-{USERNAME}")

# Check if session file exists
if os.path.exists(SESSION_PATH):
    print("Loading existing session...")
    L.load_session_from_file(USERNAME, SESSION_PATH)
else:
    print("No session found, logging in interactively...")
    L.interactive_login(USERNAME)
    L.save_session_to_file(SESSION_PATH)

# Download posts
L.download_feed_posts(max_count=5, fast_update=True,
                      post_filter=lambda post: post.viewer_has_liked)`


Error:

Retrieving pictures from your feed...
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=d6f4427fbe92d846298cf93df0b937d3&variables=%7B%7D [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=d6f4427fbe92d846298cf93df0b937d3&variables=%7B%7D [retrying; skip with ^C]
Traceback (most recent call last):
  File "C:\Users\Shree\Desktop\Insta\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=d6f4427fbe92d846298cf93df0b937d3&variables=%7B%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shree\Desktop\Insta\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=d6f4427fbe92d846298cf93df0b937d3&variables=%7B%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shree\Desktop\Insta\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=d6f4427fbe92d846298cf93df0b937d3&variables=%7B%7D

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Shree\Desktop\Insta\Download.py", line 23, in <module>
    L.download_feed_posts(max_count=5, fast_update=True,
  File "C:\Users\Shree\Desktop\Insta\.venv\Lib\site-packages\instaloader\instaloader.py", line 81, in call
    return func(instaloader, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shree\Desktop\Insta\.venv\Lib\site-packages\instaloader\instaloader.py", line 1131, in download_feed_posts
    self.posts_download_loop(self.get_feed_posts(), ":feed", fast_update, post_filter, max_count=max_count)
  File "C:\Users\Shree\Desktop\Insta\.venv\Lib\site-packages\instaloader\instaloader.py", line 1046, in posts_download_loop
    for number, post in enumerate(posts, start=start_index + 1):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shree\Desktop\Insta\.venv\Lib\site-packages\instaloader\instaloader.py", line 1095, in get_feed_posts
    data = self.context.graphql_query("d6f4427fbe92d846298cf93df0b937d3", {})["data"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shree\Desktop\Insta\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 511, in graphql_query
    resp_json = self.get_json('graphql/query',
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shree\Desktop\Insta\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shree\Desktop\Insta\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shree\Desktop\Insta\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 468, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=d6f4427fbe92d846298cf93df0b937d3&variables=%7B%7D

**Comment by SREEHARI1994** [comment]
It was all working perfectly till a few weeks ago. Pretty sure someone made some wrong commit and messed it up. This is a very serious issue and I am surprised the maintainers are not giving this any attention. Here's an easy solution that worked for me. We have no choice but to downgrade to an older version. I had to go as far back as 4.10

`pip uninstall instaloader`

`pip install instaloader==4.10`

**Comment by AndydeCleyre** [comment]
I'd be happy to use a login cookie file I have, but AFAIK there's no documentation for using such a cookie via the Python API.

I'll try to find the instance's internal `InstaloaderContext` instance, then figure out what format `update_cookies` needs.

**Comment by Benji-create** [comment]
> It was all working perfectly till a few weeks ago. Pretty sure someone made some wrong commit and messed it up. This is a very serious issue and I am surprised the maintainers are not giving this enough attention. Here's an easy solution that worked for me. We have no choice but to downgrade to an older version. I had to go as far back as 4.10
> 
> `pip uninstall instaloader`
> 
> `pip install instaloader==4.10`

Tried this. Still can't download public data. I dont have an IG Account and only trying to download public images.

After 10-15 Downloads getting the 401 Error!

Tried using proxys with  _`os.environ['http_proxy'] = proxy...`_

Didn't work either. Any updates on this?

**Comment by JCaris94** [comment]
> It was all working perfectly till a few weeks ago. Pretty sure someone made some wrong commit and messed it up. This is a very serious issue and I am surprised the maintainers are not giving this enough attention. Here's an easy solution that worked for me. We have no choice but to downgrade to an older version. I had to go as far back as 4.10
> 
> `pip uninstall instaloader`
> 
> `pip install instaloader==4.10`

I alread tried this and failed :(

Any idea to solve this?

**Comment by SREEHARI1994** [comment]
> > It was all working perfectly till a few weeks ago. Pretty sure someone made some wrong commit and messed it up. This is a very serious issue and I am surprised the maintainers are not giving this enough attention. Here's an easy solution that worked for me. We have no choice but to downgrade to an older version. I had to go as far back as 4.10
> > `pip uninstall instaloader`
> > `pip install instaloader==4.10`
> 
> I alread tried this and failed :(
> 
> Any idea to solve this?

I think that old 4.10 version of instaloader that I suggested to use as a temporary solution, only works correctly during certain time periods in a day like for eg, I am from India where it is 4am right now and it doesn't download the posts for an account for a  particular day that I want, But If I try again a few hours later it should work correctly because it worked correctly in yesterday and previous days at other times

**Comment by ozgq** [comment]
4.10/4.11 work, but not for highlights. Unless my usage is wrong:
> instaloader profile <profile> --highlights --login=<me>

**Comment by TheQL** [comment]
4.10 fails as soon as 1 account has more than 12 downloads - also for all consecutive accounts. The upcoming 4.15 branch doesn't work at all. Both without login.

**Comment by geophone** [comment]
instaloader -b Chrome <profile> works for me. I tried the session id change not sure if that was necssary

**Comment by AndydeCleyre** [comment]
Does anyone have an example of setting a cookie file when using the Python module, as opposed to the command line?

**Comment by OybekJP** [comment]
> It was all working perfectly till a few weeks ago. Pretty sure someone made some wrong commit and messed it up. This is a very serious issue and I am surprised the maintainers are not giving this enough attention. Here's an easy solution that worked for me. We have no choice but to downgrade to an older version. I had to go as far back as 4.10
> 
> `pip uninstall instaloader`
> 
> `pip install instaloader==4.10`

Thanks for sharing this workaround. 
It works up to downloading 12 posts and then it returns an error.

**Comment by bookmarks1983** [comment]
> > > It was all working perfectly till a few weeks ago. Pretty sure someone made some wrong commit and messed it up. This is a very serious issue and I am surprised the maintainers are not giving this enough attention. Here's an easy solution that worked for me. We have no choice but to downgrade to an older version. I had to go as far back as 4.10
> > > `pip uninstall instaloader`
> > > `pip install instaloader==4.10`
> > 
> > 
> > Thanks for sharing this workaround. It works up to downloading 12 posts and then it returns an error.
> 
> I think this problem has been solved in another issue of the same nature, sharing its link here- [#2501 (comment)](https://github.com/instaloader/instaloader/issues/2501#issuecomment-2707072303) But I couldn't understand this solution or what to do with it, so I am currently using instagrapi library to do my scraping, I have already written some python scripts for it and is planning to convert it into a fully functional desktop app soon. Link to my repository- https://github.com/SREEHARI1994/InstagramScraper the downloadPosts.py program in there will download all posts(excluding reels) associated with an account and downloadReels.py will quickly download all reels. If you want to try this alternate method, then I have to say a few instructions before hand
> 
> 1)instagrapi requires login and you need to edit the script with your username and password for the first time and from then on, always keep the session file in the same folder as your script and unless while debugging Google/Stack Overflow instructs you to delete the session file or if you re login via browser and thereby make session file outdated, do not ever lose the session file as it will lead to Instagram flagging you for multiple logins 2) my current version of downloadReels.py will work correctly but the program won't terminate once all reels get downloaded and you will have to manually end the program once you feel you got all reels 3)downloadStories.py and downloadbyUrl.py are the most trustworthy programs and should work perfectly to get all stories and post/reel associated with the url you gave respectively. The latter even gives all the details associated with the post such as location, caption etc as well as all the comments as a .txt file(as shown in the image in repo). I think downloadByDate.py which gets all posts or reels between two dates also works 4)downloadTagged.py,downloadHighlights.py as well as the working desktop app will be made available in the coming days 5) This is not a very hack/workaround library like instaloader and instead relies on instagrapi which is said to in turn rely on the official Instagram API, therefore I highly recommend to create a duplicate account just for this purpose, which is okay for you to lose forever(very very unlikely) and optionally use VPN (only if you have it already available). I say this only because repeated obsessive/excessive use might lead to instagram taking some action against you, which for me till now has only been minor actions like logging in on browser, add phone number followed by OTP, no access for a few hours and sometime most conveniently clicking on reCAPTCHA. Please note that I am not in any way promoting my GitHub repo, since you are still struggling with this issue, I felt obligated to reply and in order to make it in any way useful to you, I had no choice but to write all these instructions

Thanks for this solution. I've been trying to work out the previous comment's solution too, but same as you, I had no idea how to implement it.

**Comment by SamuMazzi** [comment]
For anyone wondering how to implement what's written in my comment, I'd suggest to take a look on how to read a `diff` file and how to install local packages in pip.
Otherwise go to my [PR](https://github.com/instaloader/instaloader/pull/2533) and try with my latest comment

**Comment by TheQL** [comment]
> For anyone wondering how to implement what's written in my comment, I'd suggest to take a look on how to read a `diff` file and how to install local packages in pip. Otherwise go to my [PR](https://github.com/instaloader/instaloader/pull/2533) and try with my latest comment

This worked for me in a new venv for instaloader:
`pip install git+https://github.com/instaloader/instaloader.git@refs/pull/2533/merge`

**Comment by a20084551** [comment]
> For anyone wondering how to implement what's written in my comment, I'd suggest to take a look on how to read a `diff` file and how to install local packages in pip. Otherwise go to my [PR](https://github.com/instaloader/instaloader/pull/2533) and try with my latest comment

It works — I just wanted to express my gratitude for your outstanding work.

**Comment by TheQL** [comment]
Did anybody find a workaround how we can also grab reels? As soon as I add "--reel" that query always fails.

**Comment by Rhill-2** [comment]
I'm still getting this issue. Tried downloading and replacing the files from @SamuMazzi to no avail. 

profile: JSON Query to web/search/topsearch/: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/web/search/topsearch/?context=blended&query=profile&include_reel=False&__a=1
chasethetails: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22data%22%3A%7B%22count%22%3A12%2C%22include_relationship_info%22%3Atrue%2C%22latest_besties_reel_media%22%3Atrue%2C%22latest_reel_media%22%3Atrue%7D%2C%22username%22%3A%22chasethetails%22%2C%22__relay_internal__pv__PolarisFeedShareMenurelayprovider%22%3Afalse%7D&doc_id=7898261790222653&server_timestamps=true

**Comment by g33khubber** [comment]
> Fix for python module using a venv I fixed this issue by following a post from a similar post about Unathorizied access. Login with this;
> 
> ```
> L.load_session("userName", {
>     "csrftoken": "Token",
>     "sessionid": "Token",
>     "ds_user_id": "Token",
>     "mid": "Token",
>     "ig_did": "Token"
> })
> ```
> 
> Get the tokens from browser cookie store after logging into Insta.
> 
> Go into your .venv/Lib/site-packages/instaloader folder. Open instaloadercontext.py Seach for "def login(self, user, passwd):" Delete 'sessionid': '', from
> 
> ```
> session.cookies.update({'sessionid': '', 'mid': '', 'ig_pr': '1',
>                                 'ig_vw': '1920', 'ig_cb': '1', 'csrftoken': '',
>                                 's_network': '', 'ds_user_id': ''})
> ```
> 
> so you get:
> 
> ```
> session.cookies.update({'mid': '', 'ig_pr': '1',
>                                 'ig_vw': '1920', 'ig_cb': '1', 'csrftoken': '',
>                                 's_network': '', 'ds_user_id': ''})
> ```

I'm not a technical person. is there any alternative  to this after 3 months, or would u mind posting a video on how this was done? Thanks!

**Comment by George-1717** [comment]
> > Fix for python module using a venv I fixed this issue by following a post from a similar post about Unathorizied access. Login with this;
> > ```
> > L.load_session("userName", {
> >     "csrftoken": "Token",
> >     "sessionid": "Token",
> >     "ds_user_id": "Token",
> >     "mid": "Token",
> >     "ig_did": "Token"
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Get the tokens from browser cookie store after logging into Insta.
> > Go into your .venv/Lib/site-packages/instaloader folder. Open instaloadercontext.py Seach for "def login(self, user, passwd):" Delete 'sessionid': '', from
> > ```
> > session.cookies.update({'sessionid': '', 'mid': '', 'ig_pr': '1',
> >                                 'ig_vw': '1920', 'ig_cb': '1', 'csrftoken': '',
> >                                 's_network': '', 'ds_user_id': ''})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so you get:
> > ```
> > session.cookies.update({'mid': '', 'ig_pr': '1',
> >                                 'ig_vw': '1920', 'ig_cb': '1', 'csrftoken': '',
> >                                 's_network': '', 'ds_user_id': ''})
> > ```
> 
> I'm not a technical person. is there any alternative to this after 3 months, or would u mind posting a video on how this was done? Thanks!

I haven't tried it myself but it supposedly stopped working a little while ago as reported by some people on PR https://github.com/instaloader/instaloader/pull/2533

> It stopped working. Damn Meta.
> - [IgorArnaut](https://github.com/IgorArnaut)

**Comment by IgorArnaut** [comment]
I tried it again after few weeks. No success. The browser that I mainly use is LibreWolf with "remember history" turned off.
```
instaloader rpnhma --post-filter="date_utc >= (2025, 6, 2)" --no-videos --no-video-thumbnails --no-captions --no-metadata-json --no-profile-pic
Only download posts with property "date_utc >= (2025, 6, 2)".
Hint: Login to download higher-quality versions of pictures.
[1/1] Downloading profile rpnhma
Retrieving posts from profile rpnhma.
JSON Query to graphql/query: 403 Forbidden when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22data%22%3A%7B%22count%22%3A12%2C%22include_relationship_info%22%3Atrue%2C%22latest_besties_reel_media%22%3Atrue%2C%22latest_reel_media%22%3Atrue%7D%2C%22username%22%3A%22rpnhma%22%2C%22__relay_internal__pv__PolarisFeedShareMenurelayprovider%22%3Afalse%7D&doc_id=7898261790222653&server_timestamps=true [retrying; skip with ^C]
rpnhma: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22data%22%3A%7B%22count%22%3A12%2C%22include_relationship_info%22%3Atrue%2C%22latest_besties_reel_media%22%3Atrue%2C%22latest_reel_media%22%3Atrue%7D%2C%22username%22%3A%22rpnhma%22%2C%22__relay_internal__pv__PolarisFeedShareMenurelayprovider%22%3Afalse%7D&doc_id=7898261790222653&server_timestamps=true

Errors or warnings occurred:
rpnhma: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22data%22%3A%7B%22count%22%3A12%2C%22include_relationship_info%22%3Atrue%2C%22latest_besties_reel_media%22%3Atrue%2C%22latest_reel_media%22%3Atrue%7D%2C%22username%22%3A%22rpnhma%22%2C%22__relay_internal__pv__PolarisFeedShareMenurelayprovider%22%3Afalse%7D&doc_id=7898261790222653&server_timestamps=true
```

**Comment by otsegolo** [comment]
Still an issue as far as I know, but it doesnt seem like a very actively developed project anymore.
